export const DATABASE_CREATE_REQUEST = "DATABASE_CREATE_REQUEST";
export const DATABASE_CREATE_SUCCESS = "DATABASE_CREATE_SUCCESS";
export const DATABASE_CREATE_FAIL = "DATABASE_CREATE_FAIL";
export const DATABASE_CREATE_RESET = "DATABASE_CREATE_RESET";

export const DATABASES_GET_REQUEST = "DATABASES_GET_REQUEST";
export const DATABASES_GET_SUCCESS = "DATABASES_GET_SUCCESS";
export const DATABASES_GET_FAIL = "DATABASES_GET_FAIL";
export const DATABASES_GET_RESET = "DATABASES_GET_RESET";
