export const DATABASE_CREATE_REQUEST = "DATABASE_CREATE_REQUEST";
export const DATABASE_CREATE_SUCCESS = "DATABASE_CREATE_SUCCESS";
export const DATABASE_CREATE_FAIL = "DATABASE_CREATE_FAIL";
export const DATABASE_CREATE_RESET = "DATABASE_CREATE_RESET";

export const DATABASES_GET_REQUEST = "DATABASES_GET_REQUEST";
export const DATABASES_GET_SUCCESS = "DATABASES_GET_SUCCESS";
export const DATABASES_GET_FAIL = "DATABASES_GET_FAIL";
export const DATABASES_GET_RESET = "DATABASES_GET_RESET";

export const DATABASE_GET_REQUEST = "DATABASE_GET_REQUEST";
export const DATABASE_GET_SUCCESS = "DATABASE_GET_SUCCESS";
export const DATABASE_GET_FAIL = "DATABASE_GET_FAIL";
export const DATABASE_GET_RESET = "DATABASE_GET_RESET";

export const DATABASE_DELETE_REQUEST = "DATABASE_DELETE_REQUEST";
export const DATABASE_DELETE_SUCCESS = "DATABASE_DELETE_SUCCESS";
export const DATABASE_DELETE_FAIL = "DATABASE_DELETE_FAIL";
export const DATABASE_DELETE_RESET = "DATABASE_DELETE_RESET";

export const DB_DATA_CREATE_REQUEST = "DB_DATA_CREATE_REQUEST";
export const DB_DATA_CREATE_SUCCESS = "DB_DATA_CREATE_SUCCESS";
export const DB_DATA_CREATE_FAIL = "DB_DATA_CREATE_FAIL";
export const DB_DATA_CREATE_RESET = "DB_DATA_CREATE_RESET";

export const DB_ALL_DATA_GET_REQUEST = "DB_ALL_DATA_GET_REQUEST";
export const DB_ALL_DATA_GET_SUCCESS = "DB_ALL_DATA_GET_SUCCESS";
export const DB_ALL_DATA_GET_FAIL = "DB_ALL_DATA_GET_FAIL";
export const DB_ALL_DATA_GET_RESET = "DB_ALL_DATA_GET_RESET";
